Repository The-Strategy-Unit/nhp_model, pull requests merged in 2025-07, with the labels that each got.

#423 updates variant lookup for 2022 based pop projections
  src/nhp/model/data/reference/variant_lookup.json
  tests/nhp/model/data/test_reference.py
Labels: enhancement, must

#431 adds an argument to select the projection_year for demographics
  notebooks/national_run.py
  src/nhp/model/data/databricks.py
Labels: enhancement, must

#436 uses the extracted tables for the demographic/birth data for national run
  src/nhp/model/data/databricks.py
Labels: enhancement, could

#437 improve progress reporting
  src/nhp/model/run.py
  tests/nhp/model/test_run.py
Labels: enhancement, could

#441 fix lint issues
  src/nhp/__init__.py
  src/nhp/docker/__init__.py
  src/nhp/docker/__main__.py
  src/nhp/docker/config.py
  src/nhp/docker/run.py
  src/nhp/model/__init__.py
  src/nhp/model/__main__.py
  src/nhp/model/aae.py
  src/nhp/model/activity_resampling.py
  src/nhp/model/data/__init__.py
  src/nhp/model/data/data.py
  src/nhp/model/data/databricks.py
  src/nhp/model/data/local.py
  src/nhp/model/data/reference/__init__.py
  src/nhp/model/health_status_adjustment.py
  src/nhp/model/helpers.py
  src/nhp/model/inpatients.py
  src/nhp/model/model.py
  src/nhp/model/model_iteration.py
  src/nhp/model/outpatients.py
  src/nhp/model/results.py
  src/nhp/model/run.py
  tests/nhp/model/test__main__.py
  tests/nhp/model/test_health_status_adjustment.py
Labels: enhancement, could

#444 Updated the image URL
  readme.md
Labels: enhancement, should

#450 fix issue with config tests
  src/nhp/docker/config.py
  tests/unit/nhp/docker/test_config.py
  tests/unit/nhp/docker/test_run.py
Labels: bug, should
